version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: mkdir
          command: rm -rf build && mkdir build
      - run:
          name: build
          working_directory: build
          command: cmake .. && make
      - run:
          name: test_localhost
          working_directory: build
          command: sudo ./simpleping localhost
      - run:
          name: test_127.0.0.1
          working_directory: build
          command: sudo ./simpleping 127.0.0.1
      - run:
          name: Cloudflare_DNS
          working_directory: build
          command: sudo ./simpleping 1.1.1.1
      - run:
          name: Cloudflare_DNS_v6
          working_directory: build
          command: sudo ./simpleping 2606:4700:4700::1111
      - run:
          name: Cloudflare_DNS_ttl
          working_directory: build
          command: sudo ./simpleping 1.1.1.1 3
      - run:
          name: Cloudflare_DNS_v6_ttl
          working_directory: build
          command: sudo ./simpleping 2606:4700:4700::1111 3